# Generated by Django 5.0.3 on 2026-05-16 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workspaces', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='workspaces.workspace')),
            ],
            options={
                'indexes': [models.Index(fields=['workspace', 'created_at'], name='analytics_e_workspa_b2f72a_idx'), models.Index(fields=['workspace', 'event_name'], name='analytics_e_workspa_fa1a82_idx')],
            },
        ),
    ]
